package org.openmrs.module.patientlist;

import java.io.Serializable;
import java.util.Date;
import org.openmrs.BaseOpenmrsData;

/**
 * @author levine
 */
public class PatientListItem extends BaseOpenmrsData implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private int id;
	
	private int patientId;
	
	private Date patientCallDate;
	
	private Date lastContactAttemptDate;
	
	private int contactAttempts;
	
	private int hasBeenCalled;
	
	private int drPersonId;
	
	private String voidedReason;
	
	public Date getLastContactAttemptDate() {
		return lastContactAttemptDate;
	}
	
	public void setLastContactAttemptDate(Date lastContactAttemptDate) {
		this.lastContactAttemptDate = lastContactAttemptDate;
	}
	
	public int getContactAttempts() {
		return contactAttempts;
	}
	
	public void setContactAttempts(int contactAttempts) {
		this.contactAttempts = contactAttempts;
	}
	
	public int getHasBeenCalled() {
		return hasBeenCalled;
	}
	
	public void setHasBeenCalled(int hasBeenCalled) {
		this.hasBeenCalled = hasBeenCalled;
	}
	
	public String getVoidedReason() {
		return voidedReason;
	}
	
	public void setVoidedReason(String voidedReason) {
		this.voidedReason = voidedReason;
	}
	
	public int getPatientId() {
		return patientId;
	}
	
	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}
	
	public Date getPatientCallDate() {
		return patientCallDate;
	}
	
	public void setPatientCallDate(Date patientCallDate) {
		this.patientCallDate = patientCallDate;
	}
	
	/**
	 * The primary key for this PatientListItem. Auto generated by the database.
	 * 
	 * @see org.openmrs.OpenmrsObject#getId()
	 */
	public Integer getId() {
		return id;
	}
	
	/**
	 * The primary key for this PatientListItem. If this is null, the database will generate the
	 * integer primary key because we marked the internalmessages.id column to auto_increment. <br/>
	 * <br/>
	 * 
	 * @see org.openmrs.OpenmrsObject#setId(java.lang.Integer)
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	
	public int getDrPersonId() {
		return drPersonId;
	}
	
	public void setDrPersonId(int drUserId) {
		this.drPersonId = drUserId;
	}
	
}
